### ISSUE TITLE
Document and Validate `Chips` and `Badges` Components in Pragmate-UI

### ISSUE THREAD

**Issue by jircdev** [balearesg/pragmate-ui#33]
The `Chips` and `Badges` components are currently implemented in the Pragmate-UI package, but they lack proper documentation and validation. This issue aims to address the need for comprehensive documentation and thorough validation for these components to enhance usability and developer experience.

**Tasks:**

1. **Document `Chips` Component:**
   - Create detailed documentation for the `Chips` component, including:
     - Usage instructions
     - Props description
     - Example code snippets
     - Screenshots or visual examples (if applicable)

2. **Document `Badges` Component:**
   - Develop comprehensive documentation for the `Badges` component, covering:
     - Usage guidelines
     - Props details
     - Sample code implementations
     - Visual representations (if applicable)

3. **Validate `Chips` Component:**
   - Conduct a thorough validation of the `Chips` component to ensure:
     - Functionality aligns with specifications
     - Compatibility across different browsers and environments
     - Accessibility standards are met

4. **Validate `Badges` Component:**
   - Perform extensive validation of the `Badges` component, ensuring:
     - Compliance with design and functional requirements
     - Cross-browser and environment compatibility
     - Adherence to accessibility guidelines

**Expected Outcome:**

- Well-structured and detailed documentation for both `Chips` and `Badges` components.
- Validation results confirming the functionality, compatibility, and accessibility of these components.

**Comment by Gabojcb** [comment]
# Hi, I solved issues... I send PR in branch dev

![tototo](https://github.com/balearesg/pragmate-ui/assets/111388958/ca672706-5c47-4526-9abc-c194673eeeb3)

![tototo](https://github.com/balearesg/pragmate-ui/assets/111388958/34e3c4d8-b84d-4f9e-acfc-34c8d2092917)
